/// 繁→简单字映射（自动生成：词库实际出现频次>=2 的繁体字，zhconv 转换）
/// 简体 → 繁体 反向查表：转换时用繁体字查 value 得到简体。
use std::collections::HashMap;
use std::sync::OnceLock;

fn build_map() -> HashMap<char, char> {
    let mut m = HashMap::new();
    m.insert('學', '学'); // x1863
    m.insert('體', '体'); // x754
    m.insert('數', '数'); // x687
    m.insert('動', '动'); // x624
    m.insert('國', '国'); // x612
    m.insert('論', '论'); // x606
    m.insert('義', '义'); // x589
    m.insert('爾', '尔'); // x435
    m.insert('術', '术'); // x427
    m.insert('經', '经'); // x412
    m.insert('電', '电'); // x403
    m.insert('醫', '医'); // x383
    m.insert('會', '会'); // x379
    m.insert('業', '业'); // x356
    m.insert('馬', '马'); // x353
    m.insert('機', '机'); // x349
    m.insert('氣', '气'); // x339
    m.insert('應', '应'); // x332
    m.insert('戰', '战'); // x327
    m.insert('風', '风'); // x324
    m.insert('鰕', '𫚥'); // x318
    m.insert('乾', '干'); // x298
    m.insert('質', '质'); // x294
    m.insert('間', '间'); // x290
    m.insert('線', '线'); // x285
    m.insert('亞', '亚'); // x277
    m.insert('計', '计'); // x267
    m.insert('時', '时'); // x265
    m.insert('書', '书'); // x263
    m.insert('資', '资'); // x262
    m.insert('無', '无'); // x262
    m.insert('圖', '图'); // x260
    m.insert('統', '统'); // x254
    m.insert('傳', '传'); // x248
    m.insert('療', '疗'); // x247
    m.insert('內', '内'); // x239
    m.insert('記', '记'); // x238
    m.insert('熱', '热'); // x237
    m.insert('長', '长'); // x234
    m.insert('權', '权'); // x233
    m.insert('語', '语'); // x231
    m.insert('軍', '军'); // x230
    m.insert('類', '类'); // x230
    m.insert('變', '变'); // x228
    m.insert('運', '运'); // x228
    m.insert('農', '农'); // x224
    m.insert('場', '场'); // x220
    m.insert('溫', '温'); // x217
    m.insert('環', '环'); // x216
    m.insert('說', '说'); // x215
    m.insert('產', '产'); // x213
    m.insert('藝', '艺'); // x211
    m.insert('帶', '带'); // x202
    m.insert('羅', '罗'); // x201
    m.insert('魚', '鱼'); // x199
    m.insert('紅', '红'); // x199
    m.insert('樂', '乐'); // x199
    m.insert('結', '结'); // x197
    m.insert('發', '发'); // x197
    m.insert('對', '对'); // x197
    m.insert('層', '层'); // x193
    m.insert('衛', '卫'); // x191
    m.insert('異', '异'); // x190
    m.insert('鯛', '鲷'); // x189
    m.insert('現', '现'); // x186
    m.insert('團', '团'); // x186
    m.insert('濟', '济'); // x184
    m.insert('壓', '压'); // x183
    m.insert('後', '后'); // x182
    m.insert('蘭', '兰'); // x182
    m.insert('頭', '头'); // x181
    m.insert('態', '态'); // x181
    m.insert('與', '与'); // x179
    m.insert('雲', '云'); // x174
    m.insert('標', '标'); // x173
    m.insert('構', '构'); // x173
    m.insert('達', '达'); // x173
    m.insert('實', '实'); // x173
    m.insert('黃', '黄'); // x171
    m.insert('車', '车'); // x170
    m.insert('極', '极'); // x170
    m.insert('紀', '纪'); // x169
    m.insert('畫', '画'); // x166
    m.insert('擊', '击'); // x166
    m.insert('關', '关'); // x164
    m.insert('點', '点'); // x162
    m.insert('單', '单'); // x162
    m.insert('愛', '爱'); // x160
    m.insert('則', '则'); // x159
    m.insert('轉', '转'); // x158
    m.insert('屬', '属'); // x157
    m.insert('師', '师'); // x154
    m.insert('華', '华'); // x153
    m.insert('陽', '阳'); // x152
    m.insert('歷', '历'); // x152
    m.insert('問', '问'); // x152
    m.insert('題', '题'); // x151
    m.insert('藍', '蓝'); // x151
    m.insert('測', '测'); // x150
    m.insert('積', '积'); // x150
    m.insert('際', '际'); // x149
    m.insert('東', '东'); // x147
    m.insert('組', '组'); // x147
    m.insert('狀', '状'); // x147
    m.insert('園', '园'); // x146
    m.insert('館', '馆'); // x146
    m.insert('離', '离'); // x145
    m.insert('證', '证'); // x144
    m.insert('維', '维'); // x144
    m.insert('龍', '龙'); // x144
    m.insert('雙', '双'); // x143
    m.insert('納', '纳'); // x142
    m.insert('藥', '药'); // x141
    m.insert('細', '细'); // x140
    m.insert('靈', '灵'); // x136
    m.insert('約', '约'); // x134
    m.insert('設', '设'); // x133
    m.insert('為', '为'); // x131
    m.insert('門', '门'); // x130
    m.insert('寶', '宝'); // x127
    m.insert('腦', '脑'); // x127
    m.insert('節', '节'); // x124
    m.insert('銀', '银'); // x124
    m.insert('種', '种'); // x124
    m.insert('鐵', '铁'); // x123
    m.insert('殺', '杀'); // x123
    m.insert('級', '级'); // x121
    m.insert('詩', '诗'); // x121
    m.insert('區', '区'); // x120
    m.insert('恆', '恒'); // x119
    m.insert('陳', '陈'); // x119
    m.insert('貝', '贝'); // x119
    m.insert('視', '视'); // x118
    m.insert('號', '号'); // x118
    m.insert('報', '报'); // x113
    m.insert('條', '条'); // x113
    m.insert('邊', '边'); // x113
    m.insert('塊', '块'); // x113
    m.insert('聖', '圣'); // x113
    m.insert('錄', '录'); // x112
    m.insert('護', '护'); // x112
    m.insert('觀', '观'); // x111
    m.insert('劑', '剂'); // x111
    m.insert('雞', '鸡'); // x110
    m.insert('陰', '阴'); // x109
    m.insert('灣', '湾'); // x109
    m.insert('驗', '验'); // x106
    m.insert('網', '网'); // x105
    m.insert('飛', '飞'); // x105
    m.insert('倫', '伦'); // x105
    m.insert('過', '过'); // x104
    m.insert('聯', '联'); // x104
    m.insert('蟲', '虫'); // x104
    m.insert('織', '织'); // x103
    m.insert('鏡', '镜'); // x101
    m.insert('遺', '遗'); // x100
    m.insert('準', '准'); // x100
    m.insert('鳥', '鸟'); // x100
    m.insert('覺', '觉'); // x100
    m.insert('識', '识'); // x99
    m.insert('裝', '装'); // x99
    m.insert('賽', '赛'); // x99
    m.insert('曆', '历'); // x98
    m.insert('認', '认'); // x98
    m.insert('協', '协'); // x98
    m.insert('訊', '讯'); // x97
    m.insert('脈', '脉'); // x97
    m.insert('臺', '台'); // x96
    m.insert('開', '开'); // x96
    m.insert('獎', '奖'); // x94
    m.insert('麵', '面'); // x94
    m.insert('穀', '谷'); // x94
    m.insert('夢', '梦'); // x94
    m.insert('隊', '队'); // x94
    m.insert('樹', '树'); // x93
    m.insert('島', '岛'); // x93
    m.insert('腸', '肠'); // x93
    m.insert('湯', '汤'); // x92
    m.insert('徵', '征'); // x91
    m.insert('別', '别'); // x91
    m.insert('蘇', '苏'); // x91
    m.insert('張', '张'); // x90
    m.insert('劇', '剧'); // x90
    m.insert('奧', '奥'); // x90
    m.insert('員', '员'); // x89
    m.insert('攝', '摄'); // x89
    m.insert('颱', '台'); // x87
    m.insert('價', '价'); // x87
    m.insert('調', '调'); // x87
    m.insert('庫', '库'); // x87
    m.insert('萊', '莱'); // x87
    m.insert('費', '费'); // x86
    m.insert('擬', '拟'); // x86
    m.insert('葉', '叶'); // x84
    m.insert('規', '规'); // x84
    m.insert('養', '养'); // x84
    m.insert('兒', '儿'); // x83
    m.insert('斷', '断'); // x83
    m.insert('導', '导'); // x81
    m.insert('復', '复'); // x81
    m.insert('薩', '萨'); // x81
    m.insert('務', '务'); // x81
    m.insert('諾', '诺'); // x81
    m.insert('碼', '码'); // x80
    m.insert('頓', '顿'); // x80
    m.insert('試', '试'); // x80
    m.insert('歐', '欧'); // x80
    m.insert('廚', '厨'); // x79
    m.insert('編', '编'); // x78
    m.insert('聲', '声'); // x78
    m.insert('貓', '猫'); // x78
    m.insert('強', '强'); // x77
    m.insert('總', '总'); // x77
    m.insert('進', '进'); // x77
    m.insert('軟', '软'); // x77
    m.insert('宮', '宫'); // x76
    m.insert('傷', '伤'); // x75
    m.insert('獨', '独'); // x74
    m.insert('絕', '绝'); // x74
    m.insert('參', '参'); // x73
    m.insert('預', '预'); // x73
    m.insert('紋', '纹'); // x73
    m.insert('營', '营'); // x73
    m.insert('遊', '游'); // x72
    m.insert('麥', '麦'); // x72
    m.insert('憶', '忆'); // x72
    m.insert('譜', '谱'); // x72
    m.insert('輪', '轮'); // x72
    m.insert('爭', '争'); // x71
    m.insert('來', '来'); // x71
    m.insert('虛', '虚'); // x71
    m.insert('遠', '远'); // x71
    m.insert('隕', '陨'); // x71
    m.insert('鸚', '鹦'); // x71
    m.insert('餅', '饼'); // x71
    m.insert('連', '连'); // x70
    m.insert('燒', '烧'); // x70
    m.insert('彈', '弹'); // x69
    m.insert('鱇', '𩾌'); // x69
    m.insert('議', '议'); // x69
    m.insert('陸', '陆'); // x69
    m.insert('鮈', '𬶋'); // x68
    m.insert('檢', '检'); // x68
    m.insert('筆', '笔'); // x68
    m.insert('礦', '矿'); // x68
    m.insert('漢', '汉'); // x68
    m.insert('勞', '劳'); // x68
    m.insert('氫', '氢'); // x67
    m.insert('鮟', '𩽾'); // x67
    m.insert('瑪', '玛'); // x67
    m.insert('決', '决'); // x67
    m.insert('廣', '广'); // x67
    m.insert('謝', '谢'); // x67
    m.insert('齒', '齿'); // x67
    m.insert('築', '筑'); // x67
    m.insert('換', '换'); // x66
    m.insert('萬', '万'); // x66
    m.insert('靜', '静'); // x65
    m.insert('創', '创'); // x65
    m.insert('蓋', '盖'); // x64
    m.insert('紙', '纸'); // x63
    m.insert('獵', '猎'); // x63
    m.insert('惡', '恶'); // x62
    m.insert('絲', '丝'); // x62
    m.insert('縮', '缩'); // x62
    m.insert('盤', '盘'); // x62
    m.insert('稅', '税'); // x62
    m.insert('醣', '糖'); // x61
    m.insert('財', '财'); // x61
    m.insert('戀', '恋'); // x61
    m.insert('騎', '骑'); // x61
    m.insert('階', '阶'); // x61
    m.insert('雜', '杂'); // x61
    m.insert('評', '评'); // x60
    m.insert('魯', '鲁'); // x60
    m.insert('債', '债'); // x59
    m.insert('頻', '频'); // x59
    m.insert('脫', '脱'); // x59
    m.insert('鳳', '凤'); // x59
    m.insert('腎', '肾'); // x59
    m.insert('圓', '圆'); // x57
    m.insert('戲', '戏'); // x57
    m.insert('綠', '绿'); // x57
    m.insert('陣', '阵'); // x56
    m.insert('親', '亲'); // x56
    m.insert('樓', '楼'); // x56
    m.insert('豬', '猪'); // x56
    m.insert('鬥', '斗'); // x56
    m.insert('處', '处'); // x56
    m.insert('閃', '闪'); // x56
    m.insert('寫', '写'); // x55
    m.insert('鮋', '鲉'); // x55
    m.insert('興', '兴'); // x55
    m.insert('衝', '冲'); // x55
    m.insert('險', '险'); // x55
    m.insert('飯', '饭'); // x55
    m.insert('當', '当'); // x54
    m.insert('負', '负'); // x54
    m.insert('鮠', '𬶏'); // x53
    m.insert('楊', '杨'); // x53
    m.insert('烏', '乌'); // x53
    m.insert('話', '话'); // x53
    m.insert('職', '职'); // x52
    m.insert('訴', '诉'); // x52
    m.insert('誤', '误'); // x52
    m.insert('諸', '诸'); // x52
    m.insert('壘', '垒'); // x51
    m.insert('個', '个'); // x51
    m.insert('鮄', '𫚒'); // x51
    m.insert('製', '制'); // x51
    m.insert('鏈', '链'); // x50
    m.insert('優', '优'); // x50
    m.insert('貨', '货'); // x50
    m.insert('係', '系'); // x49
    m.insert('監', '监'); // x49
    m.insert('詞', '词'); // x49
    m.insert('黨', '党'); // x49
    m.insert('稱', '称'); // x48
    m.insert('矽', '硅'); // x48
    m.insert('屍', '尸'); // x48
    m.insert('凍', '冻'); // x48
    m.insert('續', '续'); // x48
    m.insert('見', '见'); // x48
    m.insert('輝', '辉'); // x48
    m.insert('隱', '隐'); // x47
    m.insert('週', '周'); // x47
    m.insert('茲', '兹'); // x47
    m.insert('漿', '浆'); // x47
    m.insert('膠', '胶'); // x47
    m.insert('劍', '剑'); // x46
    m.insert('凱', '凯'); // x46
    m.insert('儀', '仪'); // x46
    m.insert('鈣', '钙'); // x46
    m.insert('範', '范'); // x45
    m.insert('競', '竞'); // x45
    m.insert('專', '专'); // x45
    m.insert('頂', '顶'); // x45
    m.insert('髮', '发'); // x45
    m.insert('誌', '志'); // x45
    m.insert('腳', '脚'); // x45
    m.insert('醬', '酱'); // x45
    m.insert('備', '备'); // x44
    m.insert('餘', '余'); // x44
    m.insert('複', '复'); // x44
    m.insert('偽', '伪'); // x44
    m.insert('麗', '丽'); // x44
    m.insert('橋', '桥'); // x44
    m.insert('鹽', '盐'); // x44
    m.insert('腫', '肿'); // x43
    m.insert('鮰', '𫚔'); // x43
    m.insert('滅', '灭'); // x42
    m.insert('領', '领'); // x42
    m.insert('槍', '枪'); // x42
    m.insert('臨', '临'); // x42
    m.insert('輻', '辐'); // x42
    m.insert('潛', '潜'); // x42
    m.insert('緒', '绪'); // x41
    m.insert('難', '难'); // x41
    m.insert('殼', '壳'); // x41
    m.insert('銅', '铜'); // x41
    m.insert('摺', '折'); // x40
    m.insert('廠', '厂'); // x40
    m.insert('偵', '侦'); // x40
    m.insert('錯', '错'); // x39
    m.insert('適', '适'); // x39
    m.insert('貫', '贯'); // x39
    m.insert('勢', '势'); // x39
    m.insert('觸', '触'); // x39
    m.insert('敗', '败'); // x38
    m.insert('習', '习'); // x38
    m.insert('捲', '卷'); // x38
    m.insert('終', '终'); // x38
    m.insert('頸', '颈'); // x38
    m.insert('迴', '回'); // x37
    m.insert('選', '选'); // x37
    m.insert('穩', '稳'); // x37
    m.insert('針', '针'); // x37
    m.insert('猶', '犹'); // x37
    m.insert('於', '于'); // x36
    m.insert('幾', '几'); // x36
    m.insert('煙', '烟'); // x36
    m.insert('徑', '径'); // x36
    m.insert('側', '侧'); // x36
    m.insert('眾', '众'); // x36
    m.insert('額', '额'); // x36
    m.insert('輸', '输'); // x36
    m.insert('減', '减'); // x36
    m.insert('廢', '废'); // x36
    m.insert('匯', '汇'); // x36
    m.insert('溼', '湿'); // x35
    m.insert('據', '据'); // x35
    m.insert('軸', '轴'); // x35
    m.insert('鑑', '鉴'); // x35
    m.insert('臟', '脏'); // x35
    m.insert('項', '项'); // x34
    m.insert('飲', '饮'); // x34
    m.insert('唸', '念'); // x34
    m.insert('勝', '胜'); // x34
    m.insert('幣', '币'); // x34
    m.insert('釋', '释'); // x34
    m.insert('吳', '吴'); // x34
    m.insert('鄉', '乡'); // x34
    m.insert('盜', '盗'); // x34
    m.insert('聽', '听'); // x34
    m.insert('責', '责'); // x34
    m.insert('獸', '兽'); // x34
    m.insert('軒', '轩'); // x34
    m.insert('艦', '舰'); // x34
    m.insert('鮡', '𬶐'); // x34
    m.insert('鑲', '镶'); // x33
    m.insert('許', '许'); // x33
    m.insert('綱', '纲'); // x33
    m.insert('錫', '锡'); // x33
    m.insert('鈉', '钠'); // x33
    m.insert('訓', '训'); // x33
    m.insert('桿', '杆'); // x33
    m.insert('獄', '狱'); // x33
    m.insert('診', '诊'); // x33
    m.insert('貧', '贫'); // x32
    m.insert('寧', '宁'); // x32
    m.insert('跡', '迹'); // x32
    m.insert('輔', '辅'); // x32
    m.insert('綜', '综'); // x32
    m.insert('驚', '惊'); // x32
    m.insert('鍋', '锅'); // x31
    m.insert('輯', '辑'); // x31
    m.insert('鹼', '碱'); // x31
    m.insert('鉤', '钩'); // x31
    m.insert('從', '从'); // x31
    m.insert('歸', '归'); // x31
    m.insert('讀', '读'); // x31
    m.insert('貴', '贵'); // x31
    m.insert('懼', '惧'); // x31
    m.insert('蝦', '虾'); // x31
    m.insert('濛', '蒙'); // x30
    m.insert('瓊', '琼'); // x30
    m.insert('倉', '仓'); // x30
    m.insert('傑', '杰'); // x30
    m.insert('閉', '闭'); // x30
    m.insert('載', '载'); // x30
    m.insert('譯', '译'); // x30
    m.insert('鍵', '键'); // x30
    m.insert('戶', '户'); // x30
    m.insert('韋', '韦'); // x30
    m.insert('鮑', '鲍'); // x30
    m.insert('軌', '轨'); // x30
    m.insert('擇', '择'); // x30
    m.insert('婦', '妇'); // x30
    m.insert('飾', '饰'); // x30
    m.insert('簡', '简'); // x29
    m.insert('燈', '灯'); // x29
    m.insert('邏', '逻'); // x29
    m.insert('賴', '赖'); // x29
    m.insert('謬', '谬'); // x29
    m.insert('遜', '逊'); // x29
    m.insert('榮', '荣'); // x29
    m.insert('鷹', '鹰'); // x29
    m.insert('繪', '绘'); // x29
    m.insert('純', '纯'); // x28
    m.insert('禮', '礼'); // x28
    m.insert('給', '给'); // x28
    m.insert('練', '练'); // x28
    m.insert('臘', '腊'); // x28
    m.insert('脹', '胀'); // x28
    m.insert('樣', '样'); // x28
    m.insert('叢', '丛'); // x28
    m.insert('撲', '扑'); // x27
    m.insert('緣', '缘'); // x27
    m.insert('閣', '阁'); // x27
    m.insert('繼', '继'); // x27
    m.insert('蝕', '蚀'); // x27
    m.insert('寬', '宽'); // x27
    m.insert('將', '将'); // x27
    m.insert('礙', '碍'); // x27
    m.insert('願', '愿'); // x27
    m.insert('顯', '显'); // x27
    m.insert('順', '顺'); // x27
    m.insert('劃', '划'); // x27
    m.insert('隨', '随'); // x26
    m.insert('豐', '丰'); // x26
    m.insert('兩', '两'); // x26
    m.insert('噴', '喷'); // x26
    m.insert('亂', '乱'); // x26
    m.insert('憲', '宪'); // x26
    m.insert('稜', '棱'); // x26
    m.insert('孫', '孙'); // x26
    m.insert('盧', '卢'); // x26
    m.insert('齡', '龄'); // x26
    m.insert('舊', '旧'); // x26
    m.insert('鎂', '镁'); // x26
    m.insert('鉛', '铅'); // x26
    m.insert('壞', '坏'); // x26
    m.insert('鮮', '鲜'); // x26
    m.insert('鱲', '𫚭'); // x26
    m.insert('潤', '润'); // x25
    m.insert('塵', '尘'); // x25
    m.insert('脣', '唇'); // x25
    m.insert('帳', '帐'); // x25
    m.insert('錢', '钱'); // x25
    m.insert('纖', '纤'); // x25
    m.insert('損', '损'); // x25
    m.insert('澤', '泽'); // x25
    m.insert('渦', '涡'); // x25
    m.insert('鋰', '锂'); // x25
    m.insert('霧', '雾'); // x25
    m.insert('昇', '升'); // x24
    m.insert('緩', '缓'); // x24
    m.insert('補', '补'); // x24
    m.insert('夾', '夹'); // x24
    m.insert('盪', '荡'); // x24
    m.insert('確', '确'); // x24
    m.insert('劉', '刘'); // x24
    m.insert('鎖', '锁'); // x24
    m.insert('窮', '穷'); // x24
    m.insert('慣', '惯'); // x24
    m.insert('俠', '侠'); // x24
    m.insert('溝', '沟'); // x24
    m.insert('縱', '纵'); // x24
    m.insert('誕', '诞'); // x24
    m.insert('託', '托'); // x24
    m.insert('轅', '辕'); // x24
    m.insert('鮃', '鲆'); // x24
    m.insert('鎮', '镇'); // x23
    m.insert('鑽', '钻'); // x23
    m.insert('檸', '柠'); // x23
    m.insert('汙', '污'); // x23
    m.insert('邁', '迈'); // x23
    m.insert('傭', '佣'); // x23
    m.insert('擴', '扩'); // x23
    m.insert('蒭', '𫇴'); // x23
    m.insert('濾', '滤'); // x23
    m.insert('紐', '纽'); // x23
    m.insert('嬰', '婴'); // x23
    m.insert('莖', '茎'); // x23
    m.insert('審', '审'); // x23
    m.insert('櫻', '樱'); // x23
    m.insert('歡', '欢'); // x23
    m.insert('貿', '贸'); // x23
    m.insert('魟', '𫚉'); // x22
    m.insert('幹', '干'); // x22
    m.insert('鈴', '铃'); // x22
    m.insert('鄭', '郑'); // x22
    m.insert('錐', '锥'); // x22
    m.insert('鋼', '钢'); // x22
    m.insert('滯', '滞'); // x22
    m.insert('鯨', '鲸'); // x22
    m.insert('鵝', '鹅'); // x22
    m.insert('錦', '锦'); // x22
    m.insert('濃', '浓'); // x21
    m.insert('菸', '烟'); // x21
    m.insert('釦', '扣'); // x21
    m.insert('擔', '担'); // x21
    m.insert('貼', '贴'); // x21
    m.insert('蹟', '迹'); // x21
    m.insert('啟', '启'); // x21
    m.insert('絡', '络'); // x21
    m.insert('敘', '叙'); // x21
    m.insert('齊', '齐'); // x21
    m.insert('軛', '轭'); // x21
    m.insert('篩', '筛'); // x21
    m.insert('談', '谈'); // x21
    m.insert('爐', '炉'); // x21
    m.insert('誘', '诱'); // x21
    m.insert('壽', '寿'); // x21
    m.insert('輕', '轻'); // x21
    m.insert('厭', '厌'); // x20
    m.insert('尋', '寻'); // x20
    m.insert('橫', '横'); // x20
    m.insert('鈾', '铀'); // x20
    m.insert('廳', '厅'); // x20
    m.insert('剝', '剥'); // x20
    m.insert('慶', '庆'); // x20
    m.insert('賓', '宾'); // x20
    m.insert('顏', '颜'); // x20
    m.insert('獅', '狮'); // x20
    m.insert('詐', '诈'); // x20
    m.insert('買', '买'); // x20
    m.insert('賣', '卖'); // x20
    m.insert('鯻', '𬶟'); // x20
    m.insert('購', '购'); // x19
    m.insert('捱', '挨'); // x19
    m.insert('鐘', '钟'); // x19
    m.insert('銷', '销'); // x19
    m.insert('沖', '冲'); // x19
    m.insert('滿', '满'); // x19
    m.insert('盡', '尽'); // x19
    m.insert('掃', '扫'); // x19
    m.insert('賦', '赋'); // x19
    m.insert('鉀', '钾'); // x19
    m.insert('賢', '贤'); // x19
    m.insert('蠟', '蜡'); // x19
    m.insert('揚', '扬'); // x19
    m.insert('糞', '粪'); // x19
    m.insert('搖', '摇'); // x19
    m.insert('膿', '脓'); // x19
    m.insert('鴨', '鸭'); // x19
    m.insert('鰧', '䲢'); // x19
    m.insert('彙', '汇'); // x18
    m.insert('儲', '储'); // x18
    m.insert('違', '违'); // x18
    m.insert('鈇', '𫓧'); // x18
    m.insert('鋁', '铝'); // x18
    m.insert('佔', '占'); // x18
    m.insert('韓', '韩'); // x18
    m.insert('罰', '罚'); // x18
    m.insert('殘', '残'); // x18
    m.insert('矯', '矫'); // x18
    m.insert('膚', '肤'); // x18
    m.insert('擾', '扰'); // x18
    m.insert('賊', '贼'); // x18
    m.insert('潔', '洁'); // x18
    m.insert('濕', '湿'); // x18
    m.insert('膽', '胆'); // x18
    m.insert('訟', '讼'); // x18
    m.insert('锺', '钟'); // x17
    m.insert('淨', '净'); // x17
    m.insert('钜', '巨'); // x17
    m.insert('薑', '姜'); // x17
    m.insert('簑', '蓑'); // x17
    m.insert('鷉', '䴘'); // x17
    m.insert('鸊', '䴙'); // x17
    m.insert('頁', '页'); // x17
    m.insert('郵', '邮'); // x17
    m.insert('還', '还'); // x17
    m.insert('懸', '悬'); // x17
    m.insert('淚', '泪'); // x17
    m.insert('鰻', '鳗'); // x17
    m.insert('樞', '枢'); // x17
    m.insert('蘿', '萝'); // x17
    m.insert('聞', '闻'); // x17
    m.insert('莊', '庄'); // x17
    m.insert('砲', '炮'); // x16
    m.insert('慾', '欲'); // x16
    m.insert('執', '执'); // x16
    m.insert('請', '请'); // x16
    m.insert('絃', '弦'); // x16
    m.insert('嚐', '尝'); // x16
    m.insert('閒', '闲'); // x16
    m.insert('敵', '敌'); // x16
    m.insert('遞', '递'); // x16
    m.insert('諧', '谐'); // x16
    m.insert('趨', '趋'); // x16
    m.insert('岡', '冈'); // x16
    m.insert('銣', '铷'); // x16
    m.insert('鰭', '鳍'); // x16
    m.insert('鬱', '郁'); // x16
    m.insert('況', '况'); // x16
    m.insert('蔥', '葱'); // x16
    m.insert('懷', '怀'); // x16
    m.insert('緊', '紧'); // x16
    m.insert('辯', '辩'); // x16
    m.insert('僱', '雇'); // x16
    m.insert('併', '并'); // x15
    m.insert('閱', '阅'); // x15
    m.insert('妳', '你'); // x15
    m.insert('採', '采'); // x15
    m.insert('卻', '却'); // x15
    m.insert('齋', '斋'); // x15
    m.insert('偉', '伟'); // x15
    m.insert('脩', '修'); // x15
    m.insert('瘋', '疯'); // x15
    m.insert('趙', '赵'); // x15
    m.insert('甕', '瓮'); // x15
    m.insert('疇', '畴'); // x15
    m.insert('彎', '弯'); // x15
    m.insert('畢', '毕'); // x15
    m.insert('鳴', '鸣'); // x15
    m.insert('牆', '墙'); // x15
    m.insert('奪', '夺'); // x15
    m.insert('檔', '档'); // x15
    m.insert('贈', '赠'); // x15
    m.insert('銘', '铭'); // x15
    m.insert('綿', '绵'); // x15
    m.insert('竇', '窦'); // x15
    m.insert('蓮', '莲'); // x15
    m.insert('礫', '砾'); // x15
    m.insert('災', '灾'); // x15
    m.insert('鬆', '松'); // x15
    m.insert('閩', '闽'); // x15
    m.insert('鰆', '䲠'); // x15
    m.insert('漁', '渔'); // x14
    m.insert('櫃', '柜'); // x14
    m.insert('蘋', '苹'); // x14
    m.insert('緬', '缅'); // x14
    m.insert('殭', '僵'); // x14
    m.insert('攣', '挛'); // x14
    m.insert('鎔', '镕'); // x14
    m.insert('毀', '毁'); // x14
    m.insert('漸', '渐'); // x14
    m.insert('螢', '萤'); // x14
    m.insert('媽', '妈'); // x14
    m.insert('滲', '渗'); // x14
    m.insert('龜', '龟'); // x14
    m.insert('蹤', '踪'); // x14
    m.insert('圍', '围'); // x14
    m.insert('誠', '诚'); // x14
    m.insert('謎', '谜'); // x14
    m.insert('欽', '钦'); // x14
    m.insert('擺', '摆'); // x14
    m.insert('銨', '铵'); // x14
    m.insert('銫', '铯'); // x14
    m.insert('傾', '倾'); // x14
    m.insert('欖', '榄'); // x14
    m.insert('驅', '驱'); // x14
    m.insert('鰓', '鳃'); // x14
    m.insert('蟻', '蚁'); // x14
    m.insert('淵', '渊'); // x14
    m.insert('騙', '骗'); // x14
    m.insert('鴉', '鸦'); // x14
    m.insert('塗', '涂'); // x14
    m.insert('滷', '卤'); // x14
    m.insert('鶲', '鹟'); // x14
    m.insert('煩', '烦'); // x13
    m.insert('馀', '余'); // x13
    m.insert('們', '们'); // x13
    m.insert('剛', '刚'); // x13
    m.insert('舉', '举'); // x13
    m.insert('騰', '腾'); // x13
    m.insert('枱', '台'); // x13
    m.insert('鮀', '𬶍'); // x13
    m.insert('棲', '栖'); // x13
    m.insert('繸', '䍁'); // x13
    m.insert('蒼', '苍'); // x13
    m.insert('躍', '跃'); // x13
    m.insert('飽', '饱'); // x13
    m.insert('娛', '娱'); // x13
    m.insert('龐', '庞'); // x13
    m.insert('驟', '骤'); // x13
    m.insert('顫', '颤'); // x13
    m.insert('峽', '峡'); // x13
    m.insert('辭', '辞'); // x13
    m.insert('諮', '咨'); // x13
    m.insert('獻', '献'); // x13
    m.insert('籃', '篮'); // x13
    m.insert('謀', '谋'); // x13
    m.insert('鱈', '鳕'); // x13
    m.insert('鱧', '鳢'); // x13
    m.insert('闇', '暗'); // x12
    m.insert('醯', '酰'); // x12
    m.insert('紮', '扎'); // x12
    m.insert('鉻', '铬'); // x12
    m.insert('鍾', '钟'); // x12
    m.insert('鳾', '䴓'); // x12
    m.insert('灘', '滩'); // x12
    m.insert('禦', '御'); // x12
    m.insert('鉥', '𬬸'); // x12
    m.insert('皁', '皂'); // x12
    m.insert('醜', '丑'); // x12
    m.insert('廁', '厕'); // x12
    m.insert('蔣', '蒋'); // x12
    m.insert('鱗', '鳞'); // x12
    m.insert('駝', '驼'); // x12
    m.insert('懲', '惩'); // x12
    m.insert('鏷', '镤'); // x12
    m.insert('鬚', '须'); // x12
    m.insert('釘', '钉'); // x12
    m.insert('齦', '龈'); // x12
    m.insert('憂', '忧'); // x12
    m.insert('鱷', '鳄'); // x12
    m.insert('較', '较'); // x12
    m.insert('遷', '迁'); // x12
    m.insert('鉞', '钺'); // x12
    m.insert('輦', '辇'); // x12
    m.insert('鋒', '锋'); // x12
    m.insert('顧', '顾'); // x12
    m.insert('貸', '贷'); // x12
    m.insert('訂', '订'); // x12
    m.insert('鱝', '鲼'); // x12
    m.insert('績', '绩'); // x11
    m.insert('闊', '阔'); // x11
    m.insert('夥', '伙'); // x11
    m.insert('蔔', '卜'); // x11
    m.insert('斂', '敛'); // x11
    m.insert('噹', '当'); // x11
    m.insert('瘡', '疮'); // x11
    m.insert('錶', '表'); // x11
    m.insert('爺', '爷'); // x11
    m.insert('鱊', '𫚪'); // x11
    m.insert('鹹', '咸'); // x11
    m.insert('鳶', '鸢'); // x11
    m.insert('舖', '铺'); // x11
    m.insert('歲', '岁'); // x11
    m.insert('鴗', '𫁡'); // x11
    m.insert('慄', '栗'); // x11
    m.insert('棄', '弃'); // x11
    m.insert('烴', '烃'); // x11
    m.insert('襲', '袭'); // x11
    m.insert('億', '亿'); // x11
    m.insert('堅', '坚'); // x11
    m.insert('竊', '窃'); // x11
    m.insert('疊', '叠'); // x11
    m.insert('纏', '缠'); // x11
    m.insert('韌', '韧'); // x11
    m.insert('遲', '迟'); // x11
    m.insert('黴', '霉'); // x11
    m.insert('讓', '让'); // x11
    m.insert('響', '响'); // x11
    m.insert('鉑', '铂'); // x11
    m.insert('謊', '谎'); // x11
    m.insert('嶼', '屿'); // x11
    m.insert('瀕', '濒'); // x11
    m.insert('賀', '贺'); // x11
    m.insert('貯', '贮'); // x11
    m.insert('喬', '乔'); // x11
    m.insert('滾', '滚'); // x11
    m.insert('嬌', '娇'); // x11
    m.insert('幫', '帮'); // x11
    m.insert('賭', '赌'); // x11
    m.insert('鶴', '鹤'); // x10
    m.insert('冪', '幂'); // x10
    m.insert('殢', '𣨼'); // x10
    m.insert('崗', '岗'); // x10
    m.insert('墊', '垫'); // x10
    m.insert('祿', '禄'); // x10
    m.insert('鱚', '𬶮'); // x10
    m.insert('籤', '签'); // x10
    m.insert('蒐', '搜'); // x10
    m.insert('燻', '熏'); // x10
    m.insert('燭', '烛'); // x10
    m.insert('彥', '彦'); // x10
    m.insert('沒', '没'); // x10
    m.insert('葯', '药'); // x10
    m.insert('貞', '贞'); // x10
    m.insert('廬', '庐'); // x10
    m.insert('鋸', '锯'); // x10
    m.insert('贗', '赝'); // x10
    m.insert('濁', '浊'); // x10
    m.insert('澱', '淀'); // x10
    m.insert('鬍', '胡'); // x10
    m.insert('皺', '皱'); // x10
    m.insert('暫', '暂'); // x10
    m.insert('蝸', '蜗'); // x10
    m.insert('臉', '脸'); // x10
    m.insert('兇', '凶'); // x10
    m.insert('鏢', '镖'); // x10
    m.insert('癒', '愈'); // x10
    m.insert('嶺', '岭'); // x10
    m.insert('韻', '韵'); // x10
    m.insert('繩', '绳'); // x10
    m.insert('鑒', '鉴'); // x10
    m.insert('牽', '牵'); // x10
    m.insert('颶', '飓'); // x10
    m.insert('臥', '卧'); // x10
    m.insert('曉', '晓'); // x10
    m.insert('頹', '颓'); // x10
    m.insert('鮍', '鲏'); // x10
    m.insert('潰', '溃'); // x9
    m.insert('拋', '抛'); // x9
    m.insert('棗', '枣'); // x9
    m.insert('閾', '阈'); // x9
    m.insert('薹', '苔'); // x9
    m.insert('蹠', '跖'); // x9
    m.insert('鎳', '镍'); // x9
    m.insert('倖', '幸'); // x9
    m.insert('麴', '曲'); // x9
    m.insert('硃', '朱'); // x9
    m.insert('鵰', '雕'); // x9
    m.insert('彫', '雕'); // x9
    m.insert('蝨', '虱'); // x9
    m.insert('鮣', '䲟'); // x9
    m.insert('噁', '恶'); // x9
    m.insert('甦', '苏'); // x9
    m.insert('崙', '仑'); // x9
    m.insert('駕', '驾'); // x9
    m.insert('鰏', '鲾'); // x9
    m.insert('樑', '梁'); // x9
    m.insert('齧', '啮'); // x9
    m.insert('呂', '吕'); // x9
    m.insert('廄', '厩'); // x9
    m.insert('颳', '刮'); // x9
    m.insert('痺', '痹'); // x9
    m.insert('墳', '坟'); // x9
    m.insert('掛', '挂'); // x9
    m.insert('瀝', '沥'); // x9
    m.insert('隸', '隶'); // x9
    m.insert('聰', '聪'); // x9
    m.insert('駱', '骆'); // x9
    m.insert('揮', '挥'); // x9
    m.insert('鴻', '鸿'); // x9
    m.insert('爍', '烁'); // x9
    m.insert('槓', '杠'); // x9
    m.insert('癬', '癣'); // x9
    m.insert('餓', '饿'); // x9
    m.insert('涼', '凉'); // x9
    m.insert('痙', '痉'); // x9
    m.insert('鄧', '邓'); // x9
    m.insert('貪', '贪'); // x9
    m.insert('賠', '赔'); // x9
    m.insert('詔', '诏'); // x9
    m.insert('淺', '浅'); // x9
    m.insert('禱', '祷'); // x9
    m.insert('豔', '艳'); // x9
    m.insert('吒', '咤'); // x8
    m.insert('緞', '缎'); // x8
    m.insert('燉', '炖'); // x8
    m.insert('獁', '犸'); // x8
    m.insert('顆', '颗'); // x8
    m.insert('鱂', '鳉'); // x8
    m.insert('筴', '䇲'); // x8
    m.insert('裡', '里'); // x8
    m.insert('飼', '饲'); // x8
    m.insert('讬', '托'); // x8
    m.insert('痲', '痳'); // x8
    m.insert('碩', '硕'); // x8
    m.insert('銲', '焊'); // x8
    m.insert('鴞', '鸮'); // x8
    m.insert('捨', '舍'); // x8
    m.insert('熒', '荧'); // x8
    m.insert('紗', '纱'); // x8
    m.insert('銃', '铳'); // x8
    m.insert('糾', '纠'); // x8
    m.insert('冊', '册'); // x8
    m.insert('鋪', '铺'); // x8
    m.insert('佈', '布'); // x8
    m.insert('暈', '晕'); // x8
    m.insert('鄰', '邻'); // x8
    m.insert('錳', '锰'); // x8
    m.insert('鍶', '锶'); // x8
    m.insert('鎘', '镉'); // x8
    m.insert('鈷', '钴'); // x8
    m.insert('謙', '谦'); // x8
    m.insert('擲', '掷'); // x8
    m.insert('蠍', '蝎'); // x8
    m.insert('鎧', '铠'); // x8
    m.insert('晝', '昼'); // x8
    m.insert('壺', '壶'); // x8
    m.insert('啞', '哑'); // x8
    m.insert('貢', '贡'); // x8
    m.insert('蟬', '蝉'); // x8
    m.insert('覡', '觋'); // x8
    m.insert('償', '偿'); // x8
    m.insert('礎', '础'); // x8
    m.insert('籠', '笼'); // x8
    m.insert('鈔', '钞'); // x8
    m.insert('廟', '庙'); // x8
    m.insert('轟', '轰'); // x8
    m.insert('諜', '谍'); // x8
    m.insert('糧', '粮'); // x8
    m.insert('褲', '裤'); // x8
    m.insert('鰟', '鳑'); // x8
    m.insert('鳽', '𫛚'); // x8
    m.insert('樸', '朴'); // x7
    m.insert('谘', '咨'); // x7
    m.insert('諷', '讽'); // x7
    m.insert('剎', '刹'); // x7
    m.insert('講', '讲'); // x7
    m.insert('飆', '飙'); // x7
    m.insert('銻', '锑'); // x7
    m.insert('駛', '驶'); // x7
    m.insert('詮', '诠'); // x7
    m.insert('閏', '闰'); // x7
    m.insert('鯷', '鳀'); // x7
    m.insert('譚', '谭'); // x7
    m.insert('辦', '办'); // x7
    m.insert('嘯', '啸'); // x7
    m.insert('蠙', '𧏖'); // x7
    m.insert('阨', '厄'); // x7
    m.insert('贊', '赞'); // x7
    m.insert('蠔', '蚝'); // x7
    m.insert('軋', '轧'); // x7
    m.insert('惱', '恼'); // x7
    m.insert('擠', '挤'); // x7
    m.insert('侖', '仑'); // x7
    m.insert('簫', '箫'); // x7
    m.insert('瀨', '濑'); // x7
    m.insert('軀', '躯'); // x7
    m.insert('楓', '枫'); // x7
    m.insert('濱', '滨'); // x7
    m.insert('狹', '狭'); // x7
    m.insert('窺', '窥'); // x7
    m.insert('臍', '脐'); // x7
    m.insert('謹', '谨'); // x7
    m.insert('該', '该'); // x7
    m.insert('誡', '诫'); // x7
    m.insert('販', '贩'); // x7
    m.insert('頌', '颂'); // x7
    m.insert('蕩', '荡'); // x7
    m.insert('鰋', '𫚢'); // x7
    m.insert('鰺', '鲹'); // x7
    m.insert('拚', '拼'); // x6
    m.insert('裏', '里'); // x6
    m.insert('鑷', '镊'); // x6
    m.insert('鐮', '镰'); // x6
    m.insert('踰', '逾'); // x6
    m.insert('誰', '谁'); // x6
    m.insert('畝', '亩'); // x6
    m.insert('薔', '蔷'); // x6
    m.insert('嫋', '袅'); // x6
    m.insert('巖', '岩'); // x6
    m.insert('瑯', '琅'); // x6
    m.insert('丟', '丢'); // x6
    m.insert('喚', '唤'); // x6
    m.insert('憐', '怜'); // x6
    m.insert('覈', '核'); // x6
    m.insert('獃', '呆'); // x6
    m.insert('箇', '个'); // x6
    m.insert('贏', '赢'); // x6
    m.insert('飪', '饪'); // x6
    m.insert('詢', '询'); // x6
    m.insert('贅', '赘'); // x6
    m.insert('慮', '虑'); // x6
    m.insert('鴿', '鸽'); // x6
    m.insert('濫', '滥'); // x6
    m.insert('縫', '缝'); // x6
    m.insert('馮', '冯'); // x6
    m.insert('翹', '翘'); // x6
    m.insert('釙', '钋'); // x6
    m.insert('逕', '迳'); // x6
    m.insert('羥', '羟'); // x6
    m.insert('詠', '咏'); // x6
    m.insert('芻', '刍'); // x6
    m.insert('勵', '励'); // x6
    m.insert('鵑', '鹃'); // x6
    m.insert('嚴', '严'); // x6
    m.insert('蠅', '蝇'); // x6
    m.insert('喪', '丧'); // x6
    m.insert('縣', '县'); // x6
    m.insert('鑕', '锧'); // x6
    m.insert('緯', '纬'); // x6
    m.insert('廩', '廪'); // x6
    m.insert('漬', '渍'); // x6
    m.insert('籌', '筹'); // x6
    m.insert('顎', '颚'); // x6
    m.insert('閹', '阉'); // x6
    m.insert('紹', '绍'); // x6
    m.insert('誇', '夸'); // x6
    m.insert('獲', '获'); // x6
    m.insert('勸', '劝'); // x6
    m.insert('瑣', '琐'); // x6
    m.insert('雛', '雏'); // x6
    m.insert('憑', '凭'); // x6
    m.insert('僕', '仆'); // x6
    m.insert('覽', '览'); // x6
    m.insert('輿', '舆'); // x6
    m.insert('謠', '谣'); // x6
    m.insert('攔', '拦'); // x6
    m.insert('軼', '轶'); // x6
    m.insert('挵', '弄'); // x6
    m.insert('餡', '馅'); // x6
    m.insert('鵟', '𫛭'); // x6
    m.insert('餃', '饺'); // x6
    m.insert('筍', '笋'); // x6
    m.insert('鍛', '锻'); // x5
    m.insert('鑰', '钥'); // x5
    m.insert('墮', '堕'); // x5
    m.insert('繃', '绷'); // x5
    m.insert('鍊', '炼'); // x5
    m.insert('錘', '锤'); // x5
    m.insert('墜', '坠'); // x5
    m.insert('壇', '坛'); // x5
    m.insert('洩', '泄'); // x5
    m.insert('撻', '挞'); // x5
    m.insert('紡', '纺'); // x5
    m.insert('麼', '么'); // x5
    m.insert('傘', '伞'); // x5
    m.insert('渖', '沈'); // x5
    m.insert('鑿', '凿'); // x5
    m.insert('彌', '弥'); // x5
    m.insert('渾', '浑'); // x5
    m.insert('鸞', '鸾'); // x5
    m.insert('紳', '绅'); // x5
    m.insert('剋', '克'); // x5
    m.insert('遼', '辽'); // x5
    m.insert('悅', '悦'); // x5
    m.insert('癇', '痫'); // x5
    m.insert('繆', '缪'); // x5
    m.insert('攪', '搅'); // x5
    m.insert('蝟', '猬'); // x5
    m.insert('塚', '冢'); // x5
    m.insert('襀', '𫌀'); // x5
    m.insert('酖', '鸩'); // x5
    m.insert('頑', '顽'); // x5
    m.insert('輶', '𬨎'); // x5
    m.insert('扞', '捍'); // x5
    m.insert('隄', '堤'); // x5
    m.insert('癡', '痴'); // x5
    m.insert('羶', '膻'); // x5
    m.insert('誹', '诽'); // x5
    m.insert('勻', '匀'); // x5
    m.insert('煥', '焕'); // x5
    m.insert('蘆', '芦'); // x5
    m.insert('鉅', '巨'); // x5
    m.insert('閘', '闸'); // x5
    m.insert('鴷', '䴕'); // x5
    m.insert('鰩', '鳐'); // x5
    m.insert('閔', '闵'); // x5
    m.insert('湧', '涌'); // x5
    m.insert('釀', '酿'); // x5
    m.insert('鉗', '钳'); // x5
    m.insert('薦', '荐'); // x5
    m.insert('脛', '胫'); // x5
    m.insert('蠶', '蚕'); // x5
    m.insert('淪', '沦'); // x5
    m.insert('飢', '饥'); // x5
    m.insert('橢', '椭'); // x5
    m.insert('蟎', '螨'); // x5
    m.insert('徹', '彻'); // x5
    m.insert('鯉', '鲤'); // x5
    m.insert('墾', '垦'); // x5
    m.insert('繞', '绕'); // x5
    m.insert('鱉', '鳖'); // x5
    m.insert('蕭', '萧'); // x5
    m.insert('稈', '秆'); // x5
    m.insert('饋', '馈'); // x5
    m.insert('罵', '骂'); // x5
    m.insert('棟', '栋'); // x5
    m.insert('賞', '赏'); // x5
    m.insert('煉', '炼'); // x5
    m.insert('錨', '锚'); // x5
    m.insert('癢', '痒'); // x5
    m.insert('囑', '嘱'); // x5
    m.insert('撈', '捞'); // x5
    m.insert('誥', '诰'); // x5
    m.insert('禍', '祸'); // x5
    m.insert('禎', '祯'); // x5
    m.insert('燙', '烫'); // x5
    m.insert('韃', '鞑'); // x5
    m.insert('饒', '饶'); // x5
    m.insert('磚', '砖'); // x5
    m.insert('罌', '罂'); // x5
    m.insert('緋', '绯'); // x5
    m.insert('魷', '鱿'); // x5
    m.insert('蟳', '𫊻'); // x5
    m.insert('窩', '窝'); // x5
    m.insert('鎬', '镐'); // x4
    m.insert('瞭', '了'); // x4
    m.insert('囪', '囱'); // x4
    m.insert('鯪', '鲮'); // x4
    m.insert('矇', '蒙'); // x4
    m.insert('奮', '奋'); // x4
    m.insert('暐', '𬀩'); // x4
    m.insert('遯', '遁'); // x4
    m.insert('鶗', '𫛸'); // x4
    m.insert('鎝', '锝'); // x4
    m.insert('劚', '㔉'); // x4
    m.insert('毬', '球'); // x4
    m.insert('樁', '桩'); // x4
    m.insert('蹻', '𫏋'); // x4
    m.insert('睍', '𪾢'); // x4
    m.insert('緝', '缉'); // x4
    m.insert('嚇', '吓'); // x4
    m.insert('搥', '捶'); // x4
    m.insert('檜', '桧'); // x4
    m.insert('痠', '酸'); // x4
    m.insert('蔭', '荫'); // x4
    m.insert('鶺', '鹡'); // x4
    m.insert('朮', '术'); // x4
    m.insert('櫚', '榈'); // x4
    m.insert('搨', '拓'); // x4
    m.insert('殮', '殓'); // x4
    m.insert('巔', '巅'); // x4
    m.insert('箏', '筝'); // x4
    m.insert('肐', '胳'); // x4
    m.insert('瑩', '莹'); // x4
    m.insert('瓏', '珑'); // x4
    m.insert('紛', '纷'); // x4
    m.insert('貍', '狸'); // x4
    m.insert('奼', '姹'); // x4
    m.insert('餗', '𫗧'); // x4
    m.insert('縴', '纤'); // x4
    m.insert('撧', '𪮖'); // x4
    m.insert('歛', '敛'); // x4
    m.insert('曨', '昽'); // x4
    m.insert('犛', '牦'); // x4
    m.insert('蕁', '荨'); // x4
    m.insert('鉢', '钵'); // x4
    m.insert('巘', '𪩘'); // x4
    m.insert('霑', '沾'); // x4
    m.insert('餬', '糊'); // x4
    m.insert('騃', '𫘤'); // x4
    m.insert('鵐', '鹀'); // x4
    m.insert('鷈', '䴘'); // x4
    m.insert('鸝', '鹂'); // x4
    m.insert('鞏', '巩'); // x4
    m.insert('韁', '缰'); // x4
    m.insert('遙', '遥'); // x4
    m.insert('註', '注'); // x4
    m.insert('誼', '谊'); // x4
    m.insert('贖', '赎'); // x4
    m.insert('漲', '涨'); // x4
    m.insert('瀉', '泻'); // x4
    m.insert('闌', '阑'); // x4
    m.insert('釤', '钐'); // x4
    m.insert('餾', '馏'); // x4
    m.insert('鐳', '镭'); // x4
    m.insert('鹵', '卤'); // x4
    m.insert('鑪', '𬬻'); // x4
    m.insert('鏽', '锈'); // x4
    m.insert('鉍', '铋'); // x4
    m.insert('鍺', '锗'); // x4
    m.insert('勳', '勋'); // x4
    m.insert('駭', '骇'); // x4
    m.insert('脅', '胁'); // x4
    m.insert('肅', '肃'); // x4
    m.insert('鉸', '铰'); // x4
    m.insert('絞', '绞'); // x4
    m.insert('晉', '晋'); // x4
    m.insert('魨', '鲀'); // x4
    m.insert('絨', '绒'); // x4
    m.insert('綫', '线'); // x4
    m.insert('鈦', '钛'); // x4
    m.insert('礬', '矾'); // x4
    m.insert('鳩', '鸠'); // x4
    m.insert('鏟', '铲'); // x4
    m.insert('塹', '堑'); // x4
    m.insert('壯', '壮'); // x4
    m.insert('鋇', '钡'); // x4
    m.insert('轆', '辘'); // x4
    m.insert('鶯', '莺'); // x4
    m.insert('婭', '娅'); // x4
    m.insert('瀆', '渎'); // x4
    m.insert('饗', '飨'); // x4
    m.insert('緻', '致'); // x4
    m.insert('諺', '谚'); // x4
    m.insert('荊', '荆'); // x4
    m.insert('澠', '渑'); // x4
    m.insert('匱', '匮'); // x4
    m.insert('聾', '聋'); // x4
    m.insert('譫', '谵'); // x4
    m.insert('瘍', '疡'); // x4
    m.insert('讚', '赞'); // x4
    m.insert('俁', '俣'); // x4
    m.insert('闖', '闯'); // x4
    m.insert('紺', '绀'); // x4
    m.insert('課', '课'); // x4
    m.insert('瘻', '瘘'); // x4
    m.insert('噠', '哒'); // x4
    m.insert('篤', '笃'); // x4
    m.insert('諭', '谕'); // x4
    m.insert('憤', '愤'); // x4
    m.insert('賃', '赁'); // x4
    m.insert('緘', '缄'); // x4
    m.insert('撫', '抚'); // x4
    m.insert('詛', '诅'); // x4
    m.insert('壟', '垄'); // x4
    m.insert('撥', '拨'); // x4
    m.insert('窯', '窑'); // x4
    m.insert('輛', '辆'); // x4
    m.insert('煒', '炜'); // x4
    m.insert('討', '讨'); // x4
    m.insert('馳', '驰'); // x4
    m.insert('諦', '谛'); // x4
    m.insert('詭', '诡'); // x4
    m.insert('堯', '尧'); // x4
    m.insert('訪', '访'); // x4
    m.insert('艷', '艳'); // x4
    m.insert('騷', '骚'); // x4
    m.insert('鐸', '铎'); // x4
    m.insert('濘', '泞'); // x4
    m.insert('訥', '讷'); // x4
    m.insert('賈', '贾'); // x4
    m.insert('綺', '绮'); // x4
    m.insert('蠻', '蛮'); // x4
    m.insert('懾', '慑'); // x4
    m.insert('帥', '帅'); // x4
    m.insert('釣', '钓'); // x4
    m.insert('饑', '饥'); // x4
    m.insert('靚', '靓'); // x4
    m.insert('隻', '只'); // x4
    m.insert('鴛', '鸳'); // x4
    m.insert('鴦', '鸯'); // x4
    m.insert('寵', '宠'); // x4
    m.insert('盃', '杯'); // x4
    m.insert('蔘', '参'); // x4
    m.insert('廻', '回'); // x4
    m.insert('鮸', '𩾃'); // x4
    m.insert('剉', '锉'); // x3
    m.insert('鎵', '镓'); // x3
    m.insert('樺', '桦'); // x3
    m.insert('嶇', '岖'); // x3
    m.insert('甯', '宁'); // x3
    m.insert('婁', '娄'); // x3
    m.insert('賬', '账'); // x3
    m.insert('噸', '吨'); // x3
    m.insert('鍍', '镀'); // x3
    m.insert('擄', '掳'); // x3
    m.insert('蛻', '蜕'); // x3
    m.insert('隷', '隶'); // x3
    m.insert('濺', '溅'); // x3
    m.insert('銶', '𨱇'); // x3
    m.insert('爲', '为'); // x3
    m.insert('羣', '群'); // x3
    m.insert('钁', '镢'); // x3
    m.insert('檻', '槛'); // x3
    m.insert('阬', '坑'); // x3
    m.insert('姦', '奸'); // x3
    m.insert('紓', '纾'); // x3
    m.insert('钂', '镋'); // x3
    m.insert('罷', '罢'); // x3
    m.insert('璣', '玑'); // x3
    m.insert('儉', '俭'); // x3
    m.insert('鑊', '镬'); // x3
    m.insert('吶', '呐'); // x3
    m.insert('韜', '韬'); // x3
    m.insert('鰃', '鳂'); // x3
    m.insert('兌', '兑'); // x3
    m.insert('崑', '昆'); // x3
    m.insert('鱀', '𬶨'); // x3
    m.insert('爛', '烂'); // x3
    m.insert('睏', '困'); // x3
    m.insert('閤', '合'); // x3
    m.insert('冑', '胄'); // x3
    m.insert('綏', '绥'); // x3
    m.insert('鍅', '钫'); // x3
    m.insert('騠', '𫘨'); // x3
    m.insert('並', '并'); // x3
    m.insert('癥', '症'); // x3
    m.insert('麹', '曲'); // x3
    m.insert('佇', '伫'); // x3
    m.insert('櫥', '橱'); // x3
    m.insert('璿', '璇'); // x3
    m.insert('箠', '棰'); // x3
    m.insert('鈰', '铈'); // x3
    m.insert('鉲', '锎'); // x3
    m.insert('峯', '峰'); // x3
    m.insert('巰', '巯'); // x3
    m.insert('怱', '匆'); // x3
    m.insert('摋', '𢫬'); // x3
    m.insert('琿', '珲'); // x3
    m.insert('靦', '腼'); // x3
    m.insert('慴', '慑'); // x3
    m.insert('昬', '昏'); // x3
    m.insert('棧', '栈'); // x3
    m.insert('灝', '灏'); // x3
    m.insert('筩', '筒'); // x3
    m.insert('簽', '签'); // x3
    m.insert('讒', '谗'); // x3
    m.insert('賁', '贲'); // x3
    m.insert('魎', '魉'); // x3
    m.insert('瘧', '疟'); // x3
    m.insert('穽', '阱'); // x3
    m.insert('綉', '绣'); // x3
    m.insert('緲', '缈'); // x3
    m.insert('須', '须'); // x3
    m.insert('鮊', '鲌'); // x3
    m.insert('憍', '㤭'); // x3
    m.insert('曖', '暧'); // x3
    m.insert('潑', '泼'); // x3
    m.insert('琺', '珐'); // x3
    m.insert('癱', '瘫'); // x3
    m.insert('衕', '同'); // x3
    m.insert('鍬', '锹'); // x3
    m.insert('鎓', '𬭩'); // x3
    m.insert('襬', '摆'); // x3
    m.insert('傢', '家'); // x3
    m.insert('俬', '私'); // x3
    m.insert('儂', '侬'); // x3
    m.insert('鴃', '𫛞'); // x3
    m.insert('斃', '毙'); // x3
    m.insert('弔', '吊'); // x3
    m.insert('恥', '耻'); // x3
    m.insert('稾', '稿'); // x3
    m.insert('搆', '构'); // x3
    m.insert('枴', '拐'); // x3
    m.insert('殻', '壳'); // x3
    m.insert('氈', '毡'); // x3
    m.insert('皰', '疱'); // x3
    m.insert('衊', '蔑'); // x3
    m.insert('瘓', '痪'); // x3
    m.insert('籲', '吁'); // x3
    m.insert('粵', '粤'); // x3
    m.insert('縕', '缊'); // x3
    m.insert('繐', '𰬸'); // x3
    m.insert('纍', '累'); // x3
    m.insert('孃', '娘'); // x3
    m.insert('萵', '莴'); // x3
    m.insert('薈', '荟'); // x3
    m.insert('鎌', '镰'); // x3
    m.insert('襪', '袜'); // x3
    m.insert('餔', '𫗦'); // x3
    m.insert('餽', '馈'); // x3
    m.insert('驍', '骁'); // x3
    m.insert('嬋', '婵'); // x3
    m.insert('廂', '厢'); // x3
    m.insert('暢', '畅'); // x3
    m.insert('殤', '殇'); // x3
    m.insert('滙', '汇'); // x3
    m.insert('澇', '涝'); // x3
    m.insert('袞', '衮'); // x3
    m.insert('贔', '赑'); // x3
    m.insert('銊', '𫓰'); // x3
    m.insert('閥', '阀'); // x3
    m.insert('鞦', '秋'); // x3
    m.insert('謂', '谓'); // x3
    m.insert('銳', '锐'); // x3
    m.insert('鮭', '鲑'); // x3
    m.insert('燦', '灿'); // x3
    m.insert('蠑', '蝾'); // x3
    m.insert('顳', '颞'); // x3
    m.insert('髖', '髋'); // x3
    m.insert('頰', '颊'); // x3
    m.insert('鵡', '鹉'); // x3
    m.insert('攜', '携'); // x3
    m.insert('酈', '郦'); // x3
    m.insert('鈎', '钩'); // x3
    m.insert('噓', '嘘'); // x3
    m.insert('朧', '胧'); // x3
    m.insert('懶', '懒'); // x3
    m.insert('踐', '践'); // x3
    m.insert('虜', '虏'); // x3
    m.insert('漣', '涟'); // x3
    m.insert('鵬', '鹏'); // x3
    m.insert('勛', '勋'); // x3
    m.insert('憫', '悯'); // x3
    m.insert('謨', '谟'); // x3
    m.insert('盞', '盏'); // x3
    m.insert('槳', '桨'); // x3
    m.insert('撾', '挝'); // x3
    m.insert('搗', '捣'); // x3
    m.insert('勁', '劲'); // x3
    m.insert('脇', '胁'); // x3
    m.insert('瑋', '玮'); // x3
    m.insert('鯆', '𫚙'); // x3
    m.insert('鯿', '鳊'); // x3
    m.insert('蜆', '蚬'); // x3
    m.insert('鱯', '鳠'); // x3
    m.insert('燴', '烩'); // x3
    m.insert('鶉', '鹑'); // x3
    m.insert('醃', '腌'); // x3
    m.insert('銹', '锈'); // x3
    m.insert('鮯', '𫚗'); // x3
    m.insert('鎶', '鿔'); // x2
    m.insert('鐒', '铹'); // x2
    m.insert('鰁', '鳈'); // x2
    m.insert('麽', '么'); // x2
    m.insert('榘', '矩'); // x2
    m.insert('氳', '氲'); // x2
    m.insert('旂', '旗'); // x2
    m.insert('幙', '幕'); // x2
    m.insert('飴', '饴'); // x2
    m.insert('熲', '颎'); // x2
    m.insert('牴', '抵'); // x2
    m.insert('綝', '𬘭'); // x2
    m.insert('頫', '𫖯'); // x2
    m.insert('儁', '俊'); // x2
    m.insert('槼', '椝'); // x2
    m.insert('錞', '𬭚'); // x2
    m.insert('鑼', '锣'); // x2
    m.insert('倸', '睬'); // x2
    m.insert('綈', '绨'); // x2
    m.insert('縺', '𦈐'); // x2
    m.insert('齎', '赍'); // x2
    m.insert('驎', '𬴊'); // x2
    m.insert('媿', '愧'); // x2
    m.insert('臢', '臜'); // x2
    m.insert('劄', '札'); // x2
    m.insert('彔', '录'); // x2
    m.insert('銼', '锉'); // x2
    m.insert('査', '查'); // x2
    m.insert('緹', '缇'); // x2
    m.insert('簾', '帘'); // x2
    m.insert('鉨', '鿭'); // x2
    m.insert('睪', '睾'); // x2
    m.insert('鶊', '鹒'); // x2
    m.insert('脥', '𣍰'); // x2
    m.insert('錡', '锜'); // x2
    m.insert('颭', '飐'); // x2
    m.insert('菴', '庵'); // x2
    m.insert('蜋', '螂'); // x2
    m.insert('蠀', '𧏗'); // x2
    m.insert('檵', '𪲛'); // x2
    m.insert('詝', '𬣞'); // x2
    m.insert('嵐', '岚'); // x2
    m.insert('螿', '螀'); // x2
    m.insert('頷', '颔'); // x2
    m.insert('鵚', '𪉍'); // x2
    m.insert('懞', '蒙'); // x2
    m.insert('瑇', '玳'); // x2
    m.insert('癈', '废'); // x2
    m.insert('蝀', '𬟽'); // x2
    m.insert('鋹', '𬬮'); // x2
    m.insert('顗', '𫖮'); // x2
    m.insert('鱺', '鲡'); // x2
    m.insert('俥', '伡'); // x2
    m.insert('搯', '掏'); // x2
    m.insert('樫', '㭴'); // x2
    m.insert('駁', '驳'); // x2
    m.insert('鰶', '𬶭'); // x2
    m.insert('鳷', '𫛛'); // x2
    m.insert('撦', '扯'); // x2
    m.insert('剗', '刬'); // x2
    m.insert('嘓', '啯'); // x2
    m.insert('囓', '啮'); // x2
    m.insert('徧', '遍'); // x2
    m.insert('恠', '怪'); // x2
    m.insert('慘', '惨'); // x2
    m.insert('搤', '扼'); // x2
    m.insert('揹', '背'); // x2
    m.insert('擣', '捣'); // x2
    m.insert('棊', '棋'); // x2
    m.insert('衚', '胡'); // x2
    m.insert('氂', '牦'); // x2
    m.insert('痾', '疴'); // x2
    m.insert('泝', '溯'); // x2
    m.insert('纚', '𫄥'); // x2
    m.insert('爇', '𦶟'); // x2
    m.insert('翫', '玩'); // x2
    m.insert('鼇', '鳌'); // x2
    m.insert('藷', '𫉄'); // x2
    m.insert('盨', '𪾔'); // x2
    m.insert('糲', '粝'); // x2
    m.insert('絏', '绁'); // x2
    m.insert('觝', '抵'); // x2
    m.insert('詀', '𧮪'); // x2
    m.insert('諡', '谥'); // x2
    m.insert('狥', '徇'); // x2
    m.insert('鬨', '哄'); // x2
    m.insert('蹧', '糟'); // x2
    m.insert('迻', '移'); // x2
    m.insert('鑤', '刨'); // x2
    m.insert('鰾', '鳔'); // x2
    m.insert('鱤', '鳡'); // x2
    m.insert('鴒', '鸰'); // x2
    m.insert('鶱', '𬸣'); // x2
    m.insert('鼕', '冬'); // x2
    m.insert('莧', '苋'); // x2
    m.insert('鉧', '𬭁'); // x2
    m.insert('騊', '𫘦'); // x2
    m.insert('鷓', '鹧'); // x2
    m.insert('竄', '窜'); // x2
    m.insert('鑄', '铸'); // x2
    m.insert('綁', '绑'); // x2
    m.insert('鷂', '鹞'); // x2
    m.insert('輾', '辗'); // x2
    m.insert('詳', '详'); // x2
    m.insert('籮', '箩'); // x2
    m.insert('撓', '挠'); // x2
    m.insert('釷', '钍'); // x2
    m.insert('鈧', '钪'); // x2
    m.insert('鑀', '锿'); // x2
    m.insert('鉕', '钷'); // x2
    m.insert('銪', '铕'); // x2
    m.insert('鎢', '钨'); // x2
    m.insert('鏹', '镪'); // x2
    m.insert('錠', '锭'); // x2
    m.insert('鋅', '锌'); // x2
    m.insert('鉝', '𫟷'); // x2
    m.insert('錒', '锕'); // x2
    m.insert('錀', '𬬭'); // x2
    m.insert('鐽', '𫟼'); // x2
    m.insert('鋂', '镅'); // x2
    m.insert('鎦', '镏'); // x2
    m.insert('鵲', '鹊'); // x2
    m.insert('鴯', '鸸'); // x2
    m.insert('鶓', '鹋'); // x2
    m.insert('鈍', '钝'); // x2
    m.insert('癭', '瘿'); // x2
    m.insert('嚥', '咽'); // x2
    m.insert('蟄', '蛰'); // x2
    m.insert('櫱', '蘖'); // x2
    m.insert('薊', '蓟'); // x2
    m.insert('鯽', '鲫'); // x2
    m.insert('鈞', '钧'); // x2
    m.insert('繭', '茧'); // x2
    m.insert('纓', '缨'); // x2
    m.insert('鷺', '鹭'); // x2
    m.insert('驢', '驴'); // x2
    m.insert('囉', '啰'); // x2
    m.insert('頦', '颏'); // x2
    m.insert('櫛', '栉'); // x2
    m.insert('蓀', '荪'); // x2
    m.insert('銥', '铱'); // x2
    m.insert('鈹', '铍'); // x2
    m.insert('錸', '铼'); // x2
    m.insert('堊', '垩'); // x2
    m.insert('辮', '辫'); // x2
    m.insert('磧', '碛'); // x2
    m.insert('釩', '钒'); // x2
    m.insert('銠', '铑'); // x2
    m.insert('鉬', '钼'); // x2
    m.insert('鋯', '锆'); // x2
    m.insert('纜', '缆'); // x2
    m.insert('軫', '轸'); // x2
    m.insert('謁', '谒'); // x2
    m.insert('鍀', '锝'); // x2
    m.insert('礪', '砺'); // x2
    m.insert('葦', '苇'); // x2
    m.insert('瑤', '瑶'); // x2
    m.insert('聶', '聂'); // x2
    m.insert('顓', '颛'); // x2
    m.insert('頊', '顼'); // x2
    m.insert('颮', '飑'); // x2
    m.insert('癲', '癫'); // x2
    m.insert('瞞', '瞒'); // x2
    m.insert('屓', '屃'); // x2
    m.insert('紂', '纣'); // x2
    m.insert('訣', '诀'); // x2
    m.insert('巒', '峦'); // x2
    m.insert('禪', '禅'); // x2
    m.insert('顱', '颅'); // x2
    m.insert('夠', '够'); // x2
    m.insert('瀧', '泷'); // x2
    m.insert('餵', '喂'); // x2
    m.insert('穢', '秽'); // x2
    m.insert('驕', '骄'); // x2
    m.insert('賜', '赐'); // x2
    m.insert('髕', '髌'); // x2
    m.insert('癰', '痈'); // x2
    m.insert('妝', '妆'); // x2
    m.insert('絢', '绚'); // x2
    m.insert('僂', '偻'); // x2
    m.insert('擁', '拥'); // x2
    m.insert('衞', '卫'); // x2
    m.insert('銜', '衔'); // x2
    m.insert('鄒', '邹'); // x2
    m.insert('竅', '窍'); // x2
    m.insert('頜', '颌'); // x2
    m.insert('締', '缔'); // x2
    m.insert('莢', '荚'); // x2
    m.insert('謗', '谤'); // x2
    m.insert('謄', '誊'); // x2
    m.insert('贓', '赃'); // x2
    m.insert('賄', '贿'); // x2
    m.insert('賂', '赂'); // x2
    m.insert('働', '动'); // x2
    m.insert('餉', '饷'); // x2
    m.insert('攤', '摊'); // x2
    m.insert('禿', '秃'); // x2
    m.insert('鯡', '鲱'); // x2
    m.insert('賙', '赒'); // x2
    m.insert('顛', '颠'); // x2
    m.insert('賺', '赚'); // x2
    m.insert('鷄', '鸡'); // x2
    m.insert('靄', '霭'); // x2
    m.insert('嗇', '啬'); // x2
    m.insert('轄', '辖'); // x2
    m.insert('鳧', '凫'); // x2
    m.insert('驛', '驿'); // x2
    m.insert('証', '证'); // x2
    m.insert('訛', '讹'); // x2
    m.insert('梟', '枭'); // x2
    m.insert('幟', '帜'); // x2
    m.insert('釵', '钗'); // x2
    m.insert('訶', '诃'); // x2
    m.insert('鯗', '鲞'); // x2
    m.insert('駒', '驹'); // x2
    m.insert('騶', '驺'); // x2
    m.insert('圇', '囵'); // x2
    m.insert('輓', '挽'); // x2
    m.insert('馴', '驯'); // x2
    m.insert('藪', '薮'); // x2
    m.insert('騅', '骓'); // x2
    m.insert('駢', '骈'); // x2
    m.insert('籐', '藤'); // x2
    m.insert('説', '说'); // x2
    m.insert('誨', '诲'); // x2
    m.insert('窪', '洼'); // x2
    m.insert('譽', '誉'); // x2
    m.insert('駐', '驻'); // x2
    m.insert('鶡', '鹖'); // x2
    m.insert('鈀', '钯'); // x2
    m.insert('騾', '骡'); // x2
    m.insert('殲', '歼'); // x2
    m.insert('戩', '戬'); // x2
    m.insert('曬', '晒'); // x2
    m.insert('耮', '耢'); // x2
    m.insert('籬', '篱'); // x2
    m.insert('灑', '洒'); // x2
    m.insert('鈿', '钿'); // x2
    m.insert('澆', '浇'); // x2
    m.insert('薘', '荙'); // x2
    m.insert('耬', '耧'); // x2
    m.insert('澀', '涩'); // x2
    m.insert('挾', '挟'); // x2
    m.insert('鏨', '錾'); // x2
    m.insert('熾', '炽'); // x2
    m.insert('讐', '雠'); // x2
    m.insert('祕', '秘'); // x2
    m.insert('韆', '千'); // x2
    m.insert('輩', '辈'); // x2
    m.insert('蒔', '莳'); // x2
    m.insert('嘆', '叹'); // x2
    m.insert('戧', '戗'); // x2
    m.insert('灤', '滦'); // x2
    m.insert('馭', '驭'); // x2
    m.insert('曇', '昙'); // x2
    m.insert('鵜', '鹈'); // x2
    m.insert('訝', '讶'); // x2
    m.insert('尷', '尴'); // x2
    m.insert('羨', '羡'); // x2
    m.insert('轍', '辙'); // x2
    m.insert('閡', '阂'); // x2
    m.insert('鰑', '𫚊'); // x2
    m.insert('繡', '绣'); // x2
    m.insert('錩', '锠'); // x2
    m.insert('鷿', '𬸯'); // x2
    m.insert('鸌', '鹱'); // x2
    m.insert('螞', '蚂'); // x2
    m.insert('鮆', '𫚖'); // x2
    m.insert('鱮', '𫚈'); // x2
    m.insert('鶄', '䴖'); // x2
    m.insert('燜', '焖'); // x2
    m.insert('蠣', '蛎'); // x2
    m.insert('鱠', '鲙'); // x2
    m.insert('餛', '馄'); // x2
    m.insert('飩', '饨'); // x2
    m.insert('糰', '团'); // x2
    m.insert('饃', '馍'); // x2
    m
}

/// 惰性构建的繁→简映射
pub fn simp_map() -> &'static HashMap<char, char> {
    static MAP: OnceLock<HashMap<char, char>> = OnceLock::new();
    MAP.get_or_init(build_map)
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_key_mappings() {
        assert_eq!(simp_map().get(&'學'), Some(&'学'));
        assert_eq!(simp_map().get(&'體'), Some(&'体'));
        assert_eq!(simp_map().get(&'數'), Some(&'数'));
        assert_eq!(simp_map().get(&'動'), Some(&'动'));
        assert_eq!(simp_map().get(&'國'), Some(&'国'));
        assert_eq!(simp_map().get(&'論'), Some(&'论'));
        assert_eq!(simp_map().get(&'義'), Some(&'义'));
        assert_eq!(simp_map().get(&'爾'), Some(&'尔'));
        assert_eq!(simp_map().get(&'術'), Some(&'术'));
        assert_eq!(simp_map().get(&'經'), Some(&'经'));
        assert_eq!(simp_map().get(&'電'), Some(&'电'));
        assert_eq!(simp_map().get(&'醫'), Some(&'医'));
        assert_eq!(simp_map().get(&'會'), Some(&'会'));
        assert_eq!(simp_map().get(&'業'), Some(&'业'));
        assert_eq!(simp_map().get(&'馬'), Some(&'马'));
    }
}
